DELETE FROM LINEITEM WHERE ORDERKEY>=100 AND ORDERKEY<=200;
DELETE FROM ORDERS WHERE ORDERKEY>=100 AND ORDERKEY<=200;
SELECT ORDERS.ORDERKEY, COUNT(DISTINCT LINENUMBER) AS LINECOUNT
FROM ORDERS, LINEITEM
WHERE ORDERS.ORDERKEY=LINEITEM.ORDERKEY
AND ORDERS.ORDERKEY>=50
AND ORDERS.ORDERKEY<=250
GROUP BY ORDERS.ORDERKEY
ORDER BY ORDERS.ORDERKEY;
