CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date)
SELECT FIRSTSEASON, SUM(ID-FIRSTSEASON) FROM PLAYERS GROUP BY FIRSTSEASON
